# Branch Protection Configuration
# This file documents the recommended branch protection settings for this repository

# Main Branch Protection Rules
main:
  required_status_checks:
    strict: true
    contexts:
      - "Quick PR Validation"
      - "Code Quality & Linting"
      - "Unit Tests"
      - "Integration Tests"
      - "Security Scan"
      - "Build & Package"
  
  enforce_admins: true
  
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  
  restrictions:
    users: []
    teams: []
  
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  require_signed_commits: true

# Develop Branch Protection Rules
develop:
  required_status_checks:
    strict: true
    contexts:
      - "Quick PR Validation"
      - "Code Quality & Linting"
      - "Unit Tests"
      - "Build & Package"
  
  enforce_admins: false
  
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: false
  
  restrictions:
    users: []
    teams: []
  
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  require_signed_commits: false

# Feature Branch Rules (pattern: feature/*)
feature/*:
  required_status_checks:
    strict: false
    contexts:
      - "Quick PR Validation"
  
  enforce_admins: false
  
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    require_last_push_approval: false
  
  restrictions:
    users: []
    teams: []
  
  allow_force_pushes: true
  allow_deletions: true
  block_creations: false
  required_conversation_resolution: false
  require_signed_commits: false

# Hotfix Branch Rules (pattern: hotfix/*)
hotfix/*:
  required_status_checks:
    strict: true
    contexts:
      - "Quick PR Validation"
      - "Unit Tests"
      - "Security Scan"
  
  enforce_admins: false
  
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  
  restrictions:
    users: []
    teams: []
  
  allow_force_pushes: false
  allow_deletions: false
  block_creations: false
  required_conversation_resolution: true
  require_signed_commits: true 