version: '3.8'

services:
  user-management:
    build: .
    ports:
      - "9080:9080"
    environment:
      - WLP_LOGGING_CONSOLE_LOGLEVEL=INFO
    restart: unless-stopped

networks:
  user-management-network:
    driver: bridge 