version: '3.8'

services:
  user-management:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: user-management-api-prod
    ports:
      - "9080:9080"
      - "9443:9443"
    env_file:
      - .env
    environment:
      - WLP_LOGGING_CONSOLE_LOGLEVEL=${WLP_LOGGING_CONSOLE_LOGLEVEL:-WARN}
      - WLP_LOGGING_CONSOLE_FORMAT=${WLP_LOGGING_CONSOLE_FORMAT:-json}
      - JAVA_OPTS=${JAVA_OPTS:--Xms512m -Xmx1024m -XX:+UseG1GC}
      - APP_ENV=${APP_ENV:-production}
    volumes:
      # Mount logs for external log aggregation
      - ./logs:/opt/ol/wlp/usr/servers/defaultServer/logs
      # Mount server configuration for runtime updates
      - ./src/main/liberty/config:/opt/ol/wlp/usr/servers/defaultServer/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/api/users/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - user-management-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp

networks:
  user-management-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 